name: docker image transfer
on:
  workflow_dispatch:
    inputs:
      images:
        description: "docker image"
        required: true
        default: "nginx:latest"
jobs:
  docker-image-transfer:
    name: docker image transfer
    runs-on: ubuntu-latest
    steps:
    - name: transfer
      uses: duqian42707/actions/docker-image-transfer@main
      with:
        images: ${{ github.event.inputs.images }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: swr.cn-north-4.myhuaweicloud.com
        namespace: dqv5
