name: docker image transfer using skopeo
on:
  workflow_dispatch:
    inputs:
      images:
        description: "docker image"
        required: true
        default: "docker.io/library/nginx:latest"
jobs:
  docker-image-transfer:
    name: docker image transfer
    runs-on: ubuntu-latest
    steps:
      - name: transfer
        uses: duqian42707/actions/skopeo-copy@main
        with:
          images: ${{ github.event.inputs.images }}
          registry: swr.cn-north-4.myhuaweicloud.com
          namespace: dqv5
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: public
        uses: duqian42707/actions/huaweicloud-swr-public@main
        with:
          HUAWEI_CLOUD_SDK_AK: ${{ secrets.HUAWEI_CLOUD_SDK_AK }}
          HUAWEI_CLOUD_SDK_SK: ${{ secrets.HUAWEI_CLOUD_SDK_SK }}
          HUAWEI_CLOUD_SWR_REGION: cn-north-4
          HUAWEI_CLOUD_SWR_NAMESPACE: dqv5
          HUAWEI_CLOUD_SWR_REPOSITORYS: ${{ steps.transfer.outputs.REPOSITORY_NAMES }}
